package com.kvarela.pizza_pizza;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.Boolean premium;

   public Customer()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Boolean getPremium()
   {
      return this.premium;
   }

   public void setPremium(java.lang.Boolean premium)
   {
      this.premium = premium;
   }

   public Customer(java.lang.String name, java.lang.Boolean premium)
   {
      this.name = name;
      this.premium = premium;
   }

}